version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: DeveloperEvaluation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pass@word
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  salesapi:
    build:
      context: .
      dockerfile: src/Ambev.DeveloperEvaluation.WebApi/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=DeveloperEvaluation;Username=postgres;Password=Pass@word
      - Jwt__SecretKey=DevelopEvaluation15FD$#SDevelopEvaluation15FD$#SDevelopEvaluation15FD$#S
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=YourPassword123
      - ASPNETCORE_Kestrel__Endpoints__Https__Url=https://0.0.0.0:5001
      - ASPNETCORE_Kestrel__Endpoints__Http__Url=http://0.0.0.0:5000

    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
